### ISSUE TITLE
Creating new restaurant null pointer exception

### ISSUE THREAD

**Issue by frivolta** [nomadcoders/nuber-eats-frontend#1]
Creating a new restaurant when accessing directly the page: "/add-restaurant" will trigger a null pointer exception because no cache is present.
Optimistic response with Apollo should be triggered only if the cache is already present otherwise refetch.

**Comment by serranoarevalo** [comment]
Are you watching the course as well? What is your username?

**Comment by frivolta** [comment]
Nope I cloned your repo, I am evaluating courses to train a team on graphql and stumbled upon nomadcoders

**Comment by serranoarevalo** [comment]
@frivolta  You are clearly watching the course, it's obvious from your commit history. 'evaluating' lmao. I'm glad you like the course and that you learned NestJS, hopefully you can learn how to pay for stuff one day, and since you are OK with getting other's people labor for free I hope you work for free with your clients as well.
Good luck!
